-- Update names list for Christmas Party Attendance System
-- Run this in Supabase SQL Editor

-- First, clear existing names (optional - comment out if you want to keep existing)
-- DELETE FROM names_list;

-- Insert all names
INSERT INTO names_list (name) VALUES
('Alajas, Elmer'),
('Alajas, Ezaganie'),
('Alcober, Neil'),
('Angeles, Emmanuel'),
('Angeles, Vivienne Audrey'),
('Arnaiz, Dani mari'),
('Ayeng, Raffy'),
('Basillaje, Chynna Audrey'),
('Balabag, Rey'),
('Bancod, Rey'),
('Baracena, Christian'),
('Baron, Maria Gabriela'),
('Bohatin, Gerlie'),
('Borga, Allan'),
('Brosas, Alex'),
('Bulacan, Loreli'),
('Cay, Jonas Elijah'),
('Clemente, Ma. Victoria'),
('Dalit, Lorenzo'),
('Datoy, Mary Ann M.'),
('Datu, Dino'),
('Dela Piedra, Milarosa'),
('De Vera, Josephine'),
('Dingding, Yummie'),
('Dodson, John Henry'),
('Escarlote, Mark Joseph'),
('Escuadro, Francisco'),
('Espiritu, Jocelyn (Marin)'),
('Espiritu, Luis'),
('Eugenio, Maritoni'),
('Fernando, Jefferson'),
('Formoso, Bill'),
('Francisco, Iwin'),
('Francisco, Jerry'),
('Galvan, Gene'),
('Galvan, Jelene'),
('Gamboa, Cecilio Jr.'),
('Garcia, Enrique N.'),
('Gella, Mary Rose'),
('Genova, Windsor'),
('Giongco, Nick Andrew'),
('Gulanes, Clarita'),
('Ignacio, Alwin'),
('Impuesto, Carl Michael'),
('Jose, Kathryn Kristina'),
('Kabagani, Lady Jean'),
('Kasiban, Alvin Joseph'),
('Labor, Analy'),
('Lalog, Hiyasmin'),
('Lascano, Aram Jan'),
('Llena, Rosie Ann'),
('Lozada, Luisito'),
('Lozano, Jose Aurelio'),
('Magallon, John Carlo'),
('Magadia, Carl'),
('Mago, Jason'),
('Malvar, Gabriel'),
('Mangcucang, Florian'),
('Mangcucang, Lowela'),
('Manicad, Julius'),
('Manipon, Roel'),
('Manuel, Elmer'),
('Maravilla, Gilbert'),
('Mayo, Stephanie'),
('Mendez, Romel'),
('Mendoza, Jose'),
('Meneses, Rucel'),
('Mesquiola, Rex'),
('Miranda, Genesis'),
('Montelibano, Teodoro'),
('Moran, Anna Katherina'),
('Murcia, Alvin'),
('Ojeda, Kimberly Anne'),
('Oliquino, Edjen'),
('Pascual, Ma. Pamela'),
('Pascual, Pauline Joyce'),
('Patio, Manny'),
('Payawal, Hilario'),
('Pinero, Lee Andrew'),
('Pingol, Michael'),
('Quevedo, Richbon'),
('Ramirez, Patricia May'),
('Romero, Ma. Bernadette'),
('Rosaros, Bobby'),
('Santos, Pat'),
('Songco, Pauline Inha'),
('Suing, Ivan'),
('Sumbilon, Jaimes Radhja'),
('Tabornal, Neil Kenneth'),
('Tabucol, Leopoldo'),
('Tabucol, Nomerson'),
('Togonon, Miguel Paolo'),
('Tolo, Glen'),
('Velasco, Vernon'),
('Ventura, Dinah Rowena'),
('Venturina, Edwin'),
('Villagonzalo, Jon Eli'),
('Villamente, Ferdinand'),
('Villanueva, Luis Duane'),
('Villanueva, Rhoderick'),
('Yuson, Miler')
ON CONFLICT (name) DO NOTHING;

